  CREATE TABLE "ACCOUNT_TYPE"
   (	"ACC_TYPE_ID" NUMBER(20,0) PRIMARY KEY, 
	"DESCRIPTION" VARCHAR2(20 BYTE), 
	"CREDIT_INT_RATE" NUMBER(3,5), 
	"DEBIT_INT_RATE" NUMBER(3,5), 
	"PER_DAY_CREDIT_LIM" NUMBER(20,0), 
	"PER_DAY_DEBIT_LIM" NUMBER(20,0)
   ) ;


  CREATE TABLE "ACCOUNTS"
   (	"ACC_ID" NUMBER(20,0) PRIMARY KEY, 
	"DATE_OF_OPENING" DATE, 
	"BALANCE" NUMBER, 
	"OVER_DRAFT_LIMIT" NUMBER, 
	"CUSTOMER_ID" NUMBER, 
	"ACC_TYPE_ID" VARCHAR2(20 BYTE), 
	"BRANCH_ID" NUMBER,
	FOREIGN KEY "BRANCH_ID" REFERENCES "BRANCH"("BRANCH_ID"),
	FOREIGN KEY "CUSTOMER_ID" REFERENCES "CUSTOMER"("CUSTOMER_ID"),
	FOREIGN KEY "ACC_TYPE_ID" REFERENCES "ACCOUNT_TYPE"("ACC_TYPE_ID")
   );

CREATE TABLE "BRANCH" 
   (	"BRANCH_ID" NUMBER(20,0) PRIMARY KEY, 
	"BRANCH_NAME" VARCHAR2(40 BYTE), 
	"IFSC_CODE" VARCHAR2(20 BYTE), 
	"ADDRESS_LINE_1" VARCHAR2(50 BYTE), 
	"ADDRESS_LINE_2" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"PINCODE" NUMBER(10,0),
	"MANAGER_ID" NUMBER(20,0),
	FOREIGN KEY "MANAGER_ID" REFERENCES "EMPLOYEE"("MANAGER_ID")
   );

 CREATE TABLE "EMPLOYEE" 
   (	"EMPLOYEE_ID" NUMBER(20,0) PRIMARY KEY, 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"DESIGNATION" VARCHAR2(20 BYTE), 
	"SALARY" NUMBER(20,0), 
	"BRANCH_ID" NUMBER(20,0),
	FOREIGN KEY "BRANCH_ID" REFERENCES "BRANCH"("BRANCH_ID")
   );


 CREATE TABLE "TRANSACTIONS" 
   (	"TXN_REFNUM" NUMBER PRIMARY KEY, 
	"TXN_DATE" DATE, 
	"AMOUNT" NUMBER, 
	"TXN_TYPE" VARCHAR2(20 BYTE), 
	"ACC_ID" NUMBER,
	FOREIGN KEY "ACC_ID" REFERENCES "ACCOUNT"("ACC_ID")
	);

CREATE TABLE "CUSTOMER"
(
    "CUSTOMER_ID" NUMBER(10) PRIMARY KEY,
     "FIRST_NAME" VARCHAR2(25),
     "LAST_NAME" VARCHAR2(25),
     "ADDR_LINE1" VARCHAR2(25),
     "ADDR_LINE2" VARCHAR2(25),
     "PAN_NUMBER" VARCHAR2(25),
     "CUST_TYPE" VARCHAR2(25),
     "BRANCH_ID" NUMBER,
     FOREIGN KEY "BRANCH_ID" REFERENCES "BRANCH"("BRANCH_ID")
);
    
